version: 2.1

jobs:
  lint-frontend-dockerfile:
    docker:
      - image: cimg/base:stable
    steps:
      - checkout
      - run: docker pull hadolint/hadolint
      - run: docker run --rm -i hadolint/hadolint < karsajobs-ui/Dockerfile

workflows:
  frontend-workflow:
    jobs:
      - lint-frontend-dockerfile
# VS Code Extension Version: 1.2.0
