version: 2.1

orbs:
  docker: circleci/docker@2.1.4

workflows:
  frontend-workflow:
    jobs:
      - docker/hadolint:
          dockerfiles: karsajobs-ui/Dockerfile
      - docker/publish:
          image: ghcr.io/lionelritchie29/karsajobs-ui
          dockerfile: karsajobs-ui/Dockerfile
