version: 2.1

jobs:
  lint-frontend:
    docker:
      - image: cimg/base:stable
    steps:
      - setup_remote_docker:
          version: 20.10.18
      - run: docker pull hadolint/hadolint
      - run: ls
      - run: docker run --rm -i hadolint/hadolint < ./karsajobs-ui/Dockerfile

workflows:
  frontend-workflows:
    jobs:
      - lint-frontend
