apiVersion: apps/v1
kind: Deployment
metadata:
  name: karsajobs-ui
  labels:
    app: karsajobs
    type: frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      type: frontend
  template:
    metadata:
      labels:
        app: karsajobs
        type: frontend
    spec:
      containers:
        - name: karsajobs-frontend-app
          image: ghcr.io/lionelritchie29/karsajobs-ui:latest
          ports:
            - containerPort: 8000
